version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.57-24.2
    ports:
      - "389:389"
      - "636:636"
    env_file: docker-compose.env
    volumes:
      - ./_volumes_data/var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - ./_volumes_data/var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:13.3-24
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      # - ./_volumes_data/etc/localtime:/etc/localtime:ro
      # - ./_volumes_data/etc/timezone:/etc/timezone:ro
      - ./_volumes_data/var/local/dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.24.2
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "8787:8787"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    env_file: docker-compose.env
    restart: always
    environment:
      WILDFLY_ADMIN_USER: admin
      WILDFLY_ADMIN_PASSWORD: admin
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=*:8787,server=y,suspend=n
    depends_on:
      - ldap
      - db
    volumes:
      # - ./_volumes_data/etc/localtime:/etc/localtime:ro
      # - ./_volumes_data/etc/timezone:/etc/timezone:ro
      - ./_volumes_data/var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - ./_volumes_data/var/local/dcm4chee-arc/storage:/storage
#  ui:
#    image: dcm4che/dcm4chee-arc-ui:5.24.2
#    ports:
#      - "18080:18080"
#      - "18443:18443"
#      - "19990:19990"
#      - "19993:19993"
#    env_file: docker-compose.env
#    environment:
#      DCM4CHEE_ARC_URLS: http://gunter-nb:8080/dcm4chee-arc
#      HTTP_PORT: 18080
#      HTTPS_PORT: 18443
#      MANAGEMENT_HTTP_PORT: 19990
#      MANAGEMENT_HTTPS_PORT: 19993
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - /etc/timezone:/etc/timezone:ro
#      - /var/local/dcm4chee-arc/ui:/opt/wildfly/standalone
  web:
    image: nginx:1.21.3
    volumes:
     - ./nginx/src:/usr/share/nginx/html:ro
     - ./nginx/conf/conf.d/:/etc/nginx/conf.d/
    ports:
     - "8007:80"
